name: Run Python Script with Token

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Assuming token is stored as a secret named TOKEN
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Run Python Script
        run: python generate.py ${{ secrets.TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output # The folder the action should deploy.